### ISSUE TITLE
WPUF Pro not working anymore, nobody answers on support tickets for 2 months!!!

### ISSUE THREAD

**Issue by supreme-ro** [weDevsOfficial/wp-user-frontend#1454]
[30-Apr-2024 06:24:22 UTC] PHP Warning:  foreach() argument must be of type array|object, string given in /home/ofertell/hiphopkulture.ro/wp-content/plugins/wp-user-frontend/includes/Frontend/Frontend_Account.php on line 20
[30-Apr-2024 06:24:22 UTC] PHP Fatal error:  Uncaught TypeError: in_array(): Argument #2 ($haystack) must be of type array, string given in /home/ofertell/hiphopkulture.ro/wp-content/plugins/wp-user-frontend/includes/Frontend.php:188
Stack trace:
#0 /home/ofertell/hiphopkulture.ro/wp-content/plugins/wp-user-frontend/includes/Frontend.php(188): in_array()
#1 /home/ofertell/hiphopkulture.ro/wp-includes/class-wp-hook.php(324): WeDevs\Wpuf\Frontend->show_admin_bar()
#2 /home/ofertell/hiphopkulture.ro/wp-includes/plugin.php(205): WP_Hook->apply_filters()
#3 /home/ofertell/hiphopkulture.ro/wp-includes/admin-bar.php(1378): apply_filters()
#4 /home/ofertell/hiphopkulture.ro/wp-includes/admin-bar.php(26): is_admin_bar_showing()
#5 /home/ofertell/hiphopkulture.ro/wp-includes/class-wp-hook.php(324): _wp_admin_bar_init()
#6 /home/ofertell/hiphopkulture.ro/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters()
#7 /home/ofertell/hiphopkulture.ro/wp-includes/plugin.php(517): WP_Hook->do_action()
#8 /home/ofertell/hiphopkulture.ro/wp-includes/template-loader.php(13): do_action()
#9 /home/ofertell/hiphopkulture.ro/wp-blog-header.php(19): require_once('/home/ofertell/...')
#10 /home/ofertell/hiphopkulture.ro/index.php(17): require('/home/ofertell/...')
#11 {main}
  thrown in /home/ofertell/hiphopkulture.ro/wp-content/plugins/wp-user-frontend/includes/Frontend.php on line 188
[30-Apr-2024 06:24:22 UTC] PHP Warning:  foreach() argument must be of type array|object, string given in /home/ofertell/hiphopkulture.ro/wp-content/plugins/wp-user-frontend/includes/Frontend/Frontend_Account.php on line 20

**Comment by saifislam01** [comment]
Hi @supreme-ro,

Please provide your ticket ID so that I can take the necessary steps to assist you accordingly.

**Comment by supreme-ro** [comment]
#339413

**Comment by saifislam01** [comment]
Hi @supreme-ro,

Based on our system status, I did not find this ticket ID. Could you please share the email you used to create this ticket?

**Comment by saifislam01** [comment]
Thanks for sharing the email. I've found the ticket ID and based on the information, I can see that this ticket was replied to by me.

If you update the latest version of the **WPUF free (v4.0.6)** & **Pro (v4.0.7)** plugin, your issue will be resolved. Still If you encounter the same issue then contact our support, and share the ticket ID here with the email that you used to create this ticket?

**Comment by supreme-ro** [comment]
I updated today to the latest version and my website encountered a fatal error, The errors above are from today, after the latest upgrade.
