### ISSUE TITLE
internal server error when updating post from admin dashboard.

### ISSUE THREAD

**Issue by SamTyurenkov** [weDevsOfficial/wp-user-frontend#307]
1.Create or update post A using wp user frontend form
2.Update the same post from wp-admin dashboard
3.Results in 500 error, here is the log:

```
2018/01/10 18:46:16 [error] 21347#21347: *102835 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught ArgumentCountError: Too few arguments to function WPUF_Admin_Posting::save_meta(), 1 passed in /var/www/keramika-kartina.ru/wp-includes/class-wp-hook.php on line 288 and exactly 2 expected in /var/www/keramika-kartina.ru/wp-content/plugins/wp-user-frontend/admin/posting.php:424
Stack trace:
#0 /var/www/keramika-kartina.ru/wp-includes/class-wp-hook.php(288): WPUF_Admin_Posting->save_meta(728)
#1 /var/www/keramika-kartina.ru/wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters(NULL, Array)
#2 /var/www/keramika-kartina.ru/wp-includes/plugin.php(453): WP_Hook->do_action(Array)
#3 /var/www/keramika-kartina.ru/wp-includes/post.php(3581): do_action('save_post', 728, Object(WP_Post), true)
#4 /var/www/keramika-kartina.ru/wp-includes/post.php(3654): wp_insert_post(Array, false)
#5 /var/www/keramika-kartina.ru/wp-admin/includes/post.php(377): wp_update_post(Array)
#6 /var/www/keramika-kartina.ru/wp-admin/post.php(194): edit_post()
#7 {main}
  thrown in /var/www/keramika" while reading response header from upstream, client: 127.0.0.1, server: keramika-kartina.ru, request: "POST /wp-admin/post.php HTTP/1.0", upstream: "fastcgi://unix:/run/php/php7.1-fpm.sock:", host: "keramika-kartina.ru", referrer: "https://keramika-kartina.ru/wp-admin/post.php?post=728&action=edit"
```

**Comment by itowhid06** [comment]
@SamTyurenkov, Does this issue occur when you try to create a product using the built-in WooCommerce product form?

**Comment by SamTyurenkov** [comment]
This is a custom-post type with custom-taxonomies, not a WooCommerce product. 

Also the issue only occurs when I update a post from wp-admin, which was created via wpuf form.

**Comment by shabnam611** [comment]
Hello @SamTyurenkov ! 

Can you please check theme plugin conflict? If you are not familiar with it, you can learn about it [here](https://mahbub.me/how-to-identify-a-conflicting-theme-or-plugin/) . 

If you do not find any conflicting plugin or theme, then please create a support ticket [here](https://wedevs.com/contact/). Describing your issue and our support team will reply you soon. 

Thanks for your cooperation! 
Mushrit

**Comment by SamTyurenkov** [comment]
Mushrit, 

Well I can't really check conflict, because the custom post is created by the theme. If I disable theme - I will disable that particular custom post and won't be able to see if it's conflicting or not.

Can this be a php7.1 issue instead? What I see from log - only one argument is passed instead of two

**Comment by shabnam611** [comment]
Hello @SamTyurenkov 

I understand your issue. Thanks for the update. 

Please create a support ticket [here](https://wedevs.com/contact/), we will discuss more about your issue and will reply you soon. 

Thanks!
